spring:
  application:
    name: "be"
  datasource:
    url: "jdbc:postgresql://dpg-ctjb473tq21c73e1kkbg-a.singapore-postgres.render.com:5432/test_9x5m"
    username: "test"
    password: "poEdmePryjrKE7Uz6ZSdRmVU6vt9Ohd4"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: 21124548@st.hcmuaf.edu.vn
    password: tyyb lzro flir wyzu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: "/api/v1"
  port: 8081
